import {
  GET_ALIGNMENTS,
  GET_ALIGNMENTS_SUCCESS,
  GET_ALIGNMENTS_FAILED,
  GET_ALIGNMENTS_DETAIL,
  GET_ALIGNMENTS_DETAIL_SUCCESS,
  GET_ALIGNMENTS_DETAIL_FAILED,
  POST_ALIGNMENTS_DETAIL,
  POST_ALIGNMENTS_DETAIL_SUCCESS,
  POST_ALIGNMENTS_DETAIL_FAILED,
  GET_ALIGNMENT_DOWNLOAD,
  GET_ALIGNMENT_DOWNLOAD_SUCCESS,
  GET_ALIGNMENT_DOWNLOAD_FAILED,
  GET_ALIGNMENT_DOWNLOAD_PERMISSION,
  GET_ALIGNMENT_DOWNLOAD_PERMISSION_SUCCESS,
  GET_ALIGNMENT_DOWNLOAD_PERMISSION_FAILED,
} from "../action.type";

const init = {};

export default (state = init, action) => {
  switch (action.type) {
    case GET_ALIGNMENTS:
    case GET_ALIGNMENTS_SUCCESS:
    case GET_ALIGNMENTS_FAILED:
    case GET_ALIGNMENTS_DETAIL:
    case GET_ALIGNMENTS_DETAIL_SUCCESS:
    case GET_ALIGNMENTS_DETAIL_FAILED:
    case POST_ALIGNMENTS_DETAIL:
    case POST_ALIGNMENTS_DETAIL_SUCCESS:
    case POST_ALIGNMENTS_DETAIL_FAILED:
    case GET_ALIGNMENT_DOWNLOAD:
    case GET_ALIGNMENT_DOWNLOAD_SUCCESS:
    case GET_ALIGNMENT_DOWNLOAD_FAILED:
    case GET_ALIGNMENT_DOWNLOAD_PERMISSION:
    case GET_ALIGNMENT_DOWNLOAD_PERMISSION_SUCCESS:
    case GET_ALIGNMENT_DOWNLOAD_PERMISSION_FAILED:
      return {
        ...state,
        ...action,
      };
    default:
      // return KpiState;
      return { ...state };
  }
};
