// KPI
export const SAVE_KPI = 'SAVE_KPI';
export const SAVE_KPI_SUCCESS = 'SAVE_KPI_SUCCESS';
export const SAVE_KPI_FAILED = 'SAVE_KPI_FAILED';

export const SUBMIT_KPI_PLANNING = 'SUBMIT_KPI_PLANNING';
export const SUBMIT_KPI_PLANNING_SUCCESS = 'SUBMIT_KPI_PLANNING_SUCCESS';
export const SUBMIT_KPI_PLANNING_FAILED = 'SUBMIT_KPI_PLANNING_FAILED';

export const GET_LATEST_GOAL_KPI = 'GET_LATEST_GOAL_KPI';
export const GET_LATEST_GOAL_KPI_SUCCESS = 'GET_LATEST_GOAL_KPI_SUCCESS';
export const GET_LATEST_GOAL_KPI_FAILED = 'GET_LATEST_GOAL_KPI_FAILED';

export const GET_KPI_MANAGER_LIST = 'GET_KPI_MANAGER_LIST';
export const GET_KPI_MANAGER_LIST_SUCCESS = 'GET_KPI_MANAGER_LIST_SUCCESS';
export const GET_KPI_MANAGER_LIST_FAILED = 'GET_KPI_MANAGER_LIST_FAILED';

export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';
export const DOWNLOAD_FILE_FAILED = 'DOWNLOAD_FILE_FAILED';

export const GET_KPI_LIST = 'GET_KPI_LIST';
export const GET_KPI_LIST_SUCCESS = 'GET_KPI_LIST_SUCCESS';
export const GET_KPI_LIST_FAILED = 'GET_KPI_LIST_FAILED';

export const DO_ASSESSMENT = 'DO_ASSESSMENT';
export const DO_ASSESSMENT_SUCCESS = 'DO_ASSESSMENT_SUCCESS';
export const DO_ASSESSMENT_FAILED = 'DO_ASSESSMENT_FAILED';

export const DO_ASSESSMENT_ALL = 'DO_ASSESSMENT_ALL';
export const DO_ASSESSMENT_SUCCESS_ALL = 'DO_ASSESSMENT_SUCCESS_ALL';
export const DO_ASSESSMENT_FAILED_ALL = 'DO_ASSESSMENT_FAILED_ALL';

export const GET_METRICS = 'GET_METRICS';
export const GET_METRICS_SUCCESS = 'GET_METRICS_SUCCESS';
export const GET_METRICS_FAILED = 'GET_METRICS_FAILED';

export const GET_VALUES = 'GET_VALUES';
export const GET_VALUES_SUCCESS = 'GET_VALUES_SUCCESS';
export const GET_VALUES_FAILED = 'GET_VALUES_FAILED';

export const SAVE_VALUES = 'SAVE_VALUES';
export const SAVE_VALUES_SUCCESS = 'SAVE_VALUES_SUCCESS';
export const SAVE_VALUES_FAILED = 'SAVE_VALUES_FAILED';

export const GET_RATING = 'GET_RATING';
export const GET_RATING_SUCCESS = 'GET_RATING_SUCCESS';
export const GET_RATING_FAILED = 'GET_RATING_FAILED';

export const GET_KPI_RATING = 'GET_KPI_RATING';
export const GET_KPI_RATING_SUCCESS = 'GET_KPI_RATING_SUCCESS';
export const GET_KPI_RATING_FAILED = 'GET_KPI_RATING_FAILED';

export const GET_PROPOSE_RATING = 'GET_PROPOSE_RATING';
export const GET_PROPOSE_RATING_SUCCESS = 'GET_PROPOSE_RATING_SUCCESS';
export const GET_PROPOSE_RATING_FAILED = 'GET_PROPOSE_RATING_FAILED';

export const ATTACHMENT_FILE = 'ATTACHMENT_FILE';
export const ATTACHMENT_FILE_SUCCESS = 'ATTACHMENT_FILE_SUCCESS';
export const ATTACHMENT_FILE_FAILED = 'ATTACHMENT_FILE_FAILED';

export const GET_ATTACHMENT_FILE = 'GET_ATTACHMENT_FILE';
export const GET_ATTACHMENT_FILE_SUCCESS = 'GET_ATTACHMENT_FILE_SUCCESS';
export const GET_ATTACHMENT_FILE_FAILED = 'GET_ATTACHMENT_FILE_FAILED';

export const DELETE_FILE = 'DELETE_FILE';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_FAILED = 'DELETE_FILE_FAILED';

// AUTH AND USER
export const GET_USER_INFO = 'GET_USER_INFO';
export const ERR_GET_USER_INFO = 'ERR_GET_USER_INFO';

export const getUserDetail = 'GET_USER_DETAIL';
export const errUserDetail = 'ERR_GET_USER_DETAIL';
export const startUserDetail = 'START_GET_USER_DETAIL';

export const getMyTeam = 'GET_MY_TEAM';
export const errGetMyTeam = 'ERR_GET_MY_TEAM';
export const startGetMyTeam = 'START_GET_MY_TEAM';

export const submitFeedback = 'SUBMIT_FEEDBACK';
export const successFeedback = 'SUCCESS_FEEDBACK';
export const errSubmitFeedback = 'ERR_SUBMIT_FEEDBACK';

export const getMyTeamDetail = 'GET_MY_TEAM_DETAIL';
export const errGetMyTeamDetail = 'ERR_GET_MY_TEAM_DETAIL';
export const startGetMyTeamDetail = 'START_GET_MY_TEAM_DETAIL';

export const SUBMIT_NEXT = 'SUBMIT_NEXT';
export const SUBMIT_NEXT_SUCCESS = 'SUBMIT_NEXT_SUCCESS';
export const SUBMIT_NEXT_FAILED = 'SUBMIT_NEXT_FAILED';

export const getUserKpiState = 'GET_USER_KPI_STATE';
export const errGetUserKpiState = 'ERR_GET_USER_KPI_STATE';

export const getActivity = 'GET_ACTIVITY';
export const successGetActivity = 'SUCCESS_GET_ACTIVITY';
export const errGetActivity = 'ERR_GET_ACTIVITY';

export const getStatusActivity = 'GET_STATUS_ACTIVITY';
export const successGetStatusActivity = 'SUCCESS_GET_STATUS_ACTIVITY';
export const errGetStatusActivity = 'ERR_GET_STATUS_ACTIVITY';

export const getActivityChat = 'GET_ACTIVITY_CHAT';
export const successGetActivityChat = 'SUCCESS_GET_ACTIVITY_CHAT';
export const errGetActivityChat = 'ERR_GET_ACTIVITY_CHAT';

export const doFeedbackComment = 'DO_FEEDBACK_COMMENT';
export const successFeedbackComment = 'SUCCESS_FEEDBACK_COMMENT';
export const errFeedbackComment = 'ERR_FEEDBACK_COMMENT';

export const getAchievementThread = 'GET_ACHIEVEMENT_THREAD';
export const errAchievementThread = 'ERR_ACHIEVEMENT_THREAD';
export const successAchievementThread = 'SUCCESS_ACHIEVEMENT_THREAD';

export const GET_APRAISAL_TEAM = 'GET_APRAISAL_TEAM';
export const GET_APRAISAL_TEAM_SUCCESS = 'GET_APRAISAL_TEAM_SUCCESS';
export const GET_APRAISAL_TEAM_FAILED = 'GET_APRAISAL_TEAM_FAILED';

export const GET_APRAISAL_TEAM_DETAIL = 'GET_APRAISAL_TEAM_DETAIL';
export const GET_APRAISAL_TEAM_DETAIL_SUCCESS = 'GET_APRAISAL_TEAM_DETAIL_SUCCESS';
export const GET_APRAISAL_TEAM_DETAIL_FAILED = 'GET_APRAISAL_TEAM_DETAIL_FAILED';

export const SEND_FEEDBACK_APPRAISAL = 'SEND_FEEDBACK_APPRAISAL';
export const SEND_FEEDBACK_APPRAISAL_SUCCESS = 'SEND_FEEDBACK_APPRAISAL_SUCCESS';
export const SEND_FEEDBACK_APPRAISAL_FAILED = 'SEND_FEEDBACK_APPRAISAL_FAILED';

export const APPROVE_APPRAISAL = 'APPROVE_APPRAISAL';
export const APPROVE_APPRAISAL_SUCCESS = 'APPROVE_APPRAISAL_SUCCESS';
export const APPROVE_APPRAISAL_FAILED = 'APPROVE_APPRAISAL_FAILED';

export const TEAM_ACKNOWLEDGEMENT = 'TEAM_ACKNOWLEDGEMENT';
export const TEAM_ACKNOWLEDGEMENT_SUCCESS = 'TEAM_ACKNOWLEDGEMENT_SUCCESS';
export const TEAM_ACKNOWLEDGEMENT_FAILED = 'TEAM_ACKNOWLEDGEMENT_FAILED';

export const EMP_ACKNOWLEDGEMENT = 'EMP_ACKNOWLEDGEMENT';
export const EMP_ACKNOWLEDGEMENT_SUCCESS = 'EMP_ACKNOWLEDGEMENT_SUCCESS';
export const EMP_ACKNOWLEDGEMENT_FAILED = 'EMP_ACKNOWLEDGEMENT_FAILED';

export const EMP_ACKNOWLEDGEMENT_LIST = 'EMP_ACKNOWLEDGEMENT_LIST';
export const EMP_ACKNOWLEDGEMENT_LIST_SUCCESS = 'EMP_ACKNOWLEDGEMENT_LIST_SUCCESS';
export const EMP_ACKNOWLEDGEMENT_LIST_FAILED = 'EMP_ACKNOWLEDGEMENT_LIST_FAILED';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED';

export const REVISE_KPI = 'REVISE_KPI';
export const REVISE_KPI_SUCCESS = 'REVISE_KPI_SUCCESS';
export const REVISE_KPI_FAILED = 'REVISE_KPI_FAILED';

export const GET_ALIGNMENTS = 'GET_ALIGNMENTS';
export const GET_ALIGNMENTS_SUCCESS = 'GET_ALIGNMENTS_SUCCESS';
export const GET_ALIGNMENTS_FAILED = 'GET_ALIGNMENTS_FAILED';

export const GET_ALIGNMENTS_DETAIL = 'GET_ALIGNMENTS_DETAIL';
export const GET_ALIGNMENTS_DETAIL_SUCCESS = 'GET_ALIGNMENTS_DETAIL_SUCCESS';
export const GET_ALIGNMENTS_DETAIL_FAILED = 'GET_ALIGNMENTS_DETAIL_FAILED';

export const POST_ALIGNMENTS_DETAIL = 'POST_ALIGNMENTS_DETAIL';
export const POST_ALIGNMENTS_DETAIL_SUCCESS = 'POST_ALIGNMENTS_DETAIL_SUCCESS';
export const POST_ALIGNMENTS_DETAIL_FAILED = 'POST_ALIGNMENTS_DETAIL_FAILED';

export const GET_ALIGNMENT_DOWNLOAD = 'GET_ALIGNMENT_DOWNLOAD';
export const GET_ALIGNMENT_DOWNLOAD_SUCCESS = 'GET_ALIGNMENT_DOWNLOAD_SUCCESS';
export const GET_ALIGNMENT_DOWNLOAD_FAILED = 'GET_ALIGNMENT_DOWNLOAD_FAILED';

export const GET_ALIGNMENT_DOWNLOAD_PERMISSION = 'GET_ALIGNMENT_DOWNLOAD_PERMISSION';
export const GET_ALIGNMENT_DOWNLOAD_PERMISSION_SUCCESS = 'GET_ALIGNMENT_DOWNLOAD_PERMISSION_SUCCESS';
export const GET_ALIGNMENT_DOWNLOAD_PERMISSION_FAILED = 'GET_ALIGNMENT_DOWNLOAD_PERMISSION_FAILED';

export const LOGIN_BY_AD_TOKEN = 'LOGIN_BY_AD_TOKEN';
export const LOGIN_BY_AD_TOKEN_SUCCESS = 'LOGIN_BY_AD_TOKEN_SUCCESS';
export const LOGIN_BY_AD_TOKEN_FAILED = 'LOGIN_BY_AD_TOKEN_FAILED';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const GET_CURRENT_STEP = 'GET_CURRENT_STEP';
export const GET_CURRENT_STEP_SUCCESS = 'GET_CURRENT_STEP_SUCCESS';
export const GET_CURRENT_STEP_FAILED = 'GET_CURRENT_STEP_FAILED';

export const GET_FORM_TEMPLATES = 'GET_FORM_TEMPLATES';
export const GET_FORM_TEMPLATES_SUCCESS = 'GET_FORM_TEMPLATES_SUCCESS';
export const GET_FORM_TEMPLATES_FAILED = 'GET_FORM_TEMPLATES_FAILED';

export const GET_KPI_BY_FORM_ID = 'GET_KPI_BY_FORM_ID';
export const GET_KPI_BY_FORM_ID_SUCCESS = 'GET_KPI_BY_FORM_ID_SUCCESS';
export const GET_KPI_BY_FORM_ID_FAILED = 'GET_KPI_BY_FORM_ID_FAILED';
