// KPI
export const SAVE_DRAFT = 'SAVE_DRAFT';
export const SAVE_DRAFT_SUCCESS = 'SAVE_DRAFT_SUCCESS';
export const SAVE_DRAFT_FAILED = 'SAVE_DRAFT_FAILED';

export const GET_LATEST_GOAL_KPI = 'GET_LATEST_GOAL_KPI';
export const GET_LATEST_GOAL_KPI_SUCCESS = 'GET_LATEST_GOAL_KPI_SUCCESS';
export const GET_LATEST_GOAL_KPI_FAILED = 'GET_LATEST_GOAL_KPI_FAILED';
// AUTH
export const getUserInfo = 'GET_USER_INFO';
export const errGetUserInfo = 'ERR_GET_USER_INFO';
