export const EMP_GOAL_SETTING = 'Emp Goal Setting';
export const MANAGER_GOAL_REVIEW = 'Manager Goal Review';
export const PERFORMANCE_REVIEW_EMPLOYEE = 'Performance Review Employee';
export const PERFORMANCE_REVIEW_MANAGER = 'Performance Review Manager';
export const MANAGER_ACKNOWLEDMENT = 'Manager Acknowledgement And 1:1 Meeting';
export const COMPILING_PROCESS = 'Compiling Process';
export const EMP_ACKNOWLEDGEMENT = 'Emp Acknowledgement';
export const COMPLETED = 'Completed';
export const PROGRESS_MONITORING_1 = 'Progress Monitoring 1';
export const PROGRESS_MONITORING_2 = 'Progress Monitoring 2';
export const PROGRESS_REVIEW_ALIGNMENT_1 = 'Performance Review Alignment 1';
export const PROGRESS_REVIEW_ALIGNMENT_2 = 'Performance Review Alignment 2';
export const PROGRESS_REVIEW_ALIGNMENT_1_CALLIBRATION_1 = 'Performance Review Alignment 1 (Calibration 1)';
export const PROGRESS_REVIEW_ALIGNMENT_2_CALLIBRATION_2 = 'Performance Review Alignment 2 (Calibration 2)';

export const stepKpisDropdown = [
  EMP_GOAL_SETTING,
  MANAGER_GOAL_REVIEW,
  PROGRESS_MONITORING_1,
  PROGRESS_MONITORING_2,
  PERFORMANCE_REVIEW_EMPLOYEE,
  PERFORMANCE_REVIEW_MANAGER,
  PROGRESS_REVIEW_ALIGNMENT_1,
  PROGRESS_REVIEW_ALIGNMENT_2,
  COMPILING_PROCESS,
  MANAGER_ACKNOWLEDMENT,
  EMP_ACKNOWLEDGEMENT,
  COMPLETED
];

const stepKpi = [
  EMP_GOAL_SETTING,
  MANAGER_GOAL_REVIEW,
  PERFORMANCE_REVIEW_EMPLOYEE,
  PERFORMANCE_REVIEW_MANAGER,
  COMPILING_PROCESS,
  MANAGER_ACKNOWLEDMENT,
  EMP_ACKNOWLEDGEMENT,
  COMPLETED
];

export const stepKpiMonitoring = [
  PROGRESS_MONITORING_1,
  PROGRESS_MONITORING_2
];

export const stepKpiAlignment = [
  PROGRESS_REVIEW_ALIGNMENT_1,
  PROGRESS_REVIEW_ALIGNMENT_2
];

export const menuMonitoringAllow = [
  PROGRESS_MONITORING_1,
  PROGRESS_MONITORING_2,
  PERFORMANCE_REVIEW_EMPLOYEE,
  PERFORMANCE_REVIEW_MANAGER,
  PROGRESS_REVIEW_ALIGNMENT_1,
  PROGRESS_REVIEW_ALIGNMENT_2,
  COMPILING_PROCESS,
  MANAGER_ACKNOWLEDMENT,
  EMP_ACKNOWLEDGEMENT,
  COMPLETED
];

export const menuAppraisalAllow = [
  PROGRESS_REVIEW_ALIGNMENT_1,
  PROGRESS_REVIEW_ALIGNMENT_2,
  PERFORMANCE_REVIEW_EMPLOYEE,
  PERFORMANCE_REVIEW_MANAGER,
  COMPILING_PROCESS,
  MANAGER_ACKNOWLEDMENT,
  EMP_ACKNOWLEDGEMENT,
  COMPLETED
];

export default stepKpi;
